"""Spell handler library containing all Monk spells (Windwalker and Brewmaster)."""

import math

from turn_based_wow.heroes.hero_base_stats import IBaseHero


# ---------------------------------------------------------------------------- #
#                                    Classes                                   #
# ---------------------------------------------------------------------------- #
class MonkCommonSpells(IBaseHero):
    """
    Common Spells Mixin
    This class contains the common spells and abilities of the Monk.
    """

    # ------------------------------------------------------------------------ #
    def __init__(self) -> None:
        """Initialize shared Monk stats: chi pool, health, and energy."""
        super().__init__()
        self._curr_chi = 0
        self._max_chi = 5
        self._curr_health = self.max_health
        self._curr_energy = self.max_secondary_pool

    # ------------------------------------------------------------------------ #
    def create_hero(self, hero_instance: IBaseHero):
        """Apply spec-specific stat overrides for Windwalker and Brewmaster Monks."""
        if isinstance(hero_instance, WindwalkerMonkSpells):
            hero_instance.max_health = 800
            hero_instance.max_secondary_pool = 300
            hero_instance.attack_power = 65

        elif isinstance(hero_instance, BrewmasterMonkSpells):
            hero_instance.max_health = 1100
            hero_instance.max_secondary_pool = 200
            hero_instance.attack_power = 45

        return hero_instance

    # ------------------------------------------------------------------------ #
    def is_specific_stat_spent(self, stat_value: int) -> bool:
        """
        Check if the player has enough chi to cast a spell.

        Args:
            chi_cost (int): The cost of the spell.

        Returns:
            bool: True if chi cost is spent, False otherwise.
        """
        if self._curr_chi >= stat_value:
            self._curr_chi -= stat_value
            return True

        return False

    # ------------------------------------------------------------------------ #
    def add_specific_stat(self, stat_value: int) -> None:
        """
        Adds the generated amount of chi to the currenlty available to the player. If the amount exceeds the maximum,
        the current chi is set to the maximum.

        Args:
            chi_generated (int): The amount of chi generated by the spell.
        """
        self._curr_chi += stat_value

        self._curr_chi = min(self._curr_chi, self._max_chi)

    # ------------------------------------------------------------------------ #
    def heal_up(self, heal_amount: int) -> None:
        """
        Heal the target for a certain amount of health.

        Args:
            heal_ammount (int): The amount of health to heal.
        """
        self._curr_health += heal_amount

        self._curr_health = min(self._curr_health, self.max_health)

    # ------------------------------------------------------------------------ #
    def cast_spinning_crane_kick(self) -> dict[str, int]:
        """
        Spin while kicking in the air, dealing damage to all enemies in the area.

        Returns:
            _type_: _description_
        """
        attrs = dict(self.spell_attributes)
        attrs["cooldown"] = 2
        attrs["spell_cost"] = 40
        attrs["spell_damage"] = math.ceil(self.attack_power * 40 / 100)
        self._curr_energy -= attrs["spell_cost"]

        return attrs

    # ------------------------------------------------------------------------ #
    def cast_vivify(self) -> None:
        """Heal the caster for 258% of spell power, costing 30 energy.

        The spell is silently skipped when the caster does not have enough
        energy to pay the cost.
        """

        energy_cost = 30
        amount_to_heal = math.ceil(self.spell_power * 258 / 100)
        if energy_cost >= self._curr_energy:
            self._curr_energy -= energy_cost
            self.heal_up(amount_to_heal)


# ---------------------------------------------------------------------------- #
class WindwalkerMonkSpells(MonkCommonSpells):
    # ------------------------------------------------------------------------ #
    """
    Windwalker Monk Spells
    This class contains the spells and abilities of the Windwalker Monk.
    The Windwalker Monk is a melee DPS spec that uses chi to cast spells and abilities.

    Args:
        IBaseHero (cls): _base class for all hero stats
        CommonSpellsMixin (cls): _mixin class for common spells
    """

    # ------------------------------------------------------------------------ #
    def get_name(self) -> str:
        """Return the display name of this hero class."""
        return "Windwalker Monk"

    # ------------------------------------------------------------------------ #
    def cast_tiger_palm(self) -> dict[str, int]:
        """
        Strike with the palm of you hand, dealing physical damage to the target. Generates 2 chi.

        Returns:
            tuple: spell damage, cooldown
        """
        generated_chi = 2
        attrs = dict(self.spell_attributes)
        attrs["cooldown"] = 1
        attrs["spell_cost"] = math.ceil(self.max_secondary_pool * 12 / 100)
        attrs["spell_damage"] = math.ceil(self.attack_power * 28 / 100)
        self._curr_energy -= attrs["spell_cost"]
        self.add_specific_stat(generated_chi)

        return attrs

    # ------------------------------------------------------------------------ #
    def cast_rising_sun_kick(self) -> dict[str, int]:
        """
        Kick upwards, dealing damage to the target, dealing physical damage

        Returns:
            tuple: spell damage, cooldown
        """
        attrs = dict(self.spell_attributes)
        attrs["cooldown"] = 1
        chi_cost = 2
        if self.is_specific_stat_spent(chi_cost):
            attrs["spell_damage"] = math.ceil(self.attack_power * 28 / 100)

        return attrs

    # ------------------------------------------------------------------------ #
    def cast_fists_of_fury(self) -> dict[str, int]:
        """
        Pummel all targets in front of you, dealing physical damage.

        Returns:
            tuple: spell damage, cooldown
        """
        chi_cost = 3
        attrs = dict(self.spell_attributes)
        attrs["cooldown"] = 2
        if self.is_specific_stat_spent(chi_cost):
            attrs["spell_damage"] = math.ceil(self.attack_power * 138 / 100)

        return attrs

    # ------------------------------------------------------------------------ #
    def cast_whirling_dragon_punch(self) -> dict[str, int]:
        """
        Perform a devastationg whirling upward stike, dealing damage to all targets in front of you.

        Returns:
            tuple: spell damage, cooldown
        """
        attrs = dict(self.spell_attributes)
        attrs["cooldown"] = 5
        attrs["spell_damage"] = math.ceil(self.attack_power * 230 / 100)

        return attrs


# ---------------------------------------------------------------------------- #
class BrewmasterMonkSpells(MonkCommonSpells):
    # ------------------------------------------------------------------------ #
    """
    Brewmaster Monk Spells
    This class contains the spells and abilities of the Brewmaster Monk.
    The Brewmaster Monk is a tank spec that uses chi to cast spells and abilities.

    Args:
        IBaseHero (cls): _base class for all hero stats
        CommonSpellsMixin (cls): _mixin class for common spells
    """

    # ------------------------------------------------------------------------ #
    def get_name(self) -> str:
        """Return the display name of this hero class."""
        return "Brewmaster Monk"

    # ------------------------------------------------------------------------ #
    def cast_rushing_jade_wind(self) -> dict[str, int]:
        """
        Summon a swirling wind around you, dealing damage to all enemies in the area.

        Returns:
            tuple: spell damage, cooldown
        """
        chi_cost = 1
        attrs = dict(self.spell_attributes)
        attrs["cooldown"] = 1
        if self.is_specific_stat_spent(chi_cost):
            attrs["spell_damage"] = math.ceil(self.attack_power * 14 / 100)

        return attrs

    # ------------------------------------------------------------------------ #
    def cast_chi_burst(self) -> dict[str, int]:
        """
        Launch a burst of chi energy, dealing damage to all enemies in the area.

        Returns:
            tuple: spell damage, cooldown
        """
        attrs = dict(self.spell_attributes)
        attrs["cooldown"] = 7
        attrs["spell_damage"] = math.ceil(self.attack_power * 280 / 100)

        return attrs

    # ------------------------------------------------------------------------ #
    def cast_keg_smash(self) -> dict[str, int]:
        """Smash the target with your keg, dealing damage and reducing incoming damage by 30% for 1 turn.

        Returns:
            dict: spell_cost, spell_damage, cooldown, damage_reduction
        """

        spell_cost = 40
        attrs = dict(self.spell_attributes)
        attrs["spell_cost"] = spell_cost
        attrs["cooldown"] = 3
        attrs["spell_damage"] = math.ceil(self.attack_power * 100 / 100)
        self._curr_energy -= spell_cost
        attrs["damage_reduction"] = 30

        return attrs

    # ------------------------------------------------------------------------ #
    def cast_blackout_kick(self) -> dict[str, int]:
        """
        Kick the target with a blast of chi, dealing damage to the target.

        Returns:
            tuple: spell damage, cooldown
        """
        chi_cost = 3
        attrs = dict(self.spell_attributes)
        attrs["cooldown"] = 1
        if self.is_specific_stat_spent(chi_cost):
            attrs["spell_damage"] = math.ceil(self.attack_power * 85 / 100)

        return attrs

    # ------------------------------------------------------------------------ #
    def cast_breath_of_fire(self) -> dict[str, int]:
        """
        Breath fire on the target, dealing fire damage infront of the hero.

        Returns:
            tuple: spell damage, cooldown
        """
        attrs = dict(self.spell_attributes)
        attrs["cooldown"] = 5
        attrs["spell_damage"] = math.ceil(self.attack_power * 54 / 100)

        return attrs
